youtube:
  - url: https://www.youtube.com/watch?v=I8AzqgoWZds
    name: "HydroCam Introduction"

knowledge_bases:
  # Add your 3 knowledge base root URLs here
  # - url: https://hydrocam.paro.nl/
  #   name: "HydroCam knowledge base"
